/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   mandelbrot.c                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: cde-migu <cde-migu@student.42madrid.com    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/08/20 16:31:41 by cde-migu          #+#    #+#             */
/*   Updated: 2024/08/29 15:42:54 by cde-migu         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "fractol.h"

float	get_index(int n, double c)
{
	if (n == 0)
		return (0);
	else
		return (get_index(n - 1, c) * get_index(n - 1, c) + c);
}

//This->yage has been generated by running the recursive formula up to twenty ->yes per pixel


//comprueba si c pertenece al conjunto mandelbrot
bool	is_stable(double c, int max_iterations)
{
    double z = 0.0;
    for (int i = 0; i < max_iterations; ++i) {
        z = pow(z, 2) + c;
        if (fabs(z) > 2.0) {
            return false;
        }
    }
    return true;
}

// int	mandelbrot(int max, t_complex_num z, t_complex_num c)
// {
// 	if (max > 0)
// 		return (mandelbrot(max -1, complex_mandel_formula(z, c), c));
// 	else if (abs_complex_val(z) > 2)
// 		return (0);
// 	else
// 		return (1);
// }



// temp_x = (z.x * z.x) - (z->y * z->y);
// 		z->y = 2 * z.x * z->y;
// 		z.x = temp_x;

// 		z.x += c.x;
// 		z->y += c->y;

// int	main()
// {
// 	t_fractal z;
// 	t_fractal c;
// 	double temp_x;

// 	z.x = 0;
// 	z->y = 0;

// 	c.x = 5;
// 	c->y = 2;

// 	for (int i = 0; i < 3; ++i)
// 	{
// 		// z = z^2 + c --> (a+b)2 = a^2 + b^2 + 2ab,
// 		// pero->y^2 siempre es -1
// 		// x^2 - y^2 + 2xy
// 		temp_x = (z.x * z.x) - (z->y * z->y);
// 		z->y = 2 * z.x * z->y;
// 		z.x = temp_x;

// 		z.x += c.x;
// 		z->y += c->y;

// 		printf("iteration n -> %d \t x %f->yaginary %f \n", i, z.x, z->y);
// 	}
// }
