/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   mandelbrot.c                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: cde-migu <cde-migu@student.42madrid.com    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/08/20 16:31:41 by cde-migu          #+#    #+#             */
/*   Updated: 2024/08/22 17:14:18 by cde-migu         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "fractol.h"

float	get_index(int n, double c)
{
	if (n == 0)
		return (0);
	else
		return (get_index(n - 1, c) * get_index(n - 1, c) + c);
}

//This image has been generated by running the recursive formula up to twenty times per pixel


//comprueba si c pertenece al conjunto mandelbrot
bool is_stable(double c, int max_iterations) {
    double z = 0.0;
    for (int i = 0; i < max_iterations; ++i) {
        z = pow(z, 2) + c;
        if (fabs(z) > 2.0) {
            return false;
        }
    }
    return true;
}

t_complex_num complex_pow_2(t_complex_num nb)
{
	double temp_real;

	temp_real = (nb.real * nb.real) - (nb.im * nb.im);
	nb.im = 2 * nb.real * nb.im;
	nb.real = temp_real;
	return (nb);
}

t_complex_num complex_mandel_formula(t_complex_num z, t_complex_num c)
{
	double temp_real;
	
	temp_real = (z.real * z.real) - (z.im * z.im);
	z.im = 2 * z.real * z.im;
	z.real = temp_real;

	z.real += c.real;
	z.im += c.im;
	return (z);
}

t_complex_num mandelbrot (int max, t_complex_num z_in, t_complex_num c)
{
	if (max > 0)
		return (mandelbrot(max -1, complex_mandel_formula(z_in, c), c));
	else if (pow(z_in.real, 2) + pow(z_in.im, 2) > 4)
		return (0);
	else
		return (1);
}
// temp_real = (z.real * z.real) - (z.im * z.im);
// 		z.im = 2 * z.real * z.im;
// 		z.real = temp_real;

// 		z.real += c.real;
// 		z.im += c.im;

// int	main()
// {
// 	t_complex_num z;
// 	t_complex_num c;
// 	double temp_real;

// 	z.real = 0;
// 	z.im = 0;

// 	c.real = 5;
// 	c.im = 2;

// 	for (int i = 0; i < 3; ++i)
// 	{
// 		// z = z^2 + c --> (a+b)2 = a^2 + b^2 + 2ab,
// 		// pero im^2 siempre es -1
// 		// x^2 - y^2 + 2xy
// 		temp_real = (z.real * z.real) - (z.im * z.im);
// 		z.im = 2 * z.real * z.im;
// 		z.real = temp_real;

// 		z.real += c.real;
// 		z.im += c.im;

// 		printf("iteration n -> %d \t real %f imaginary %f \n", i, z.real, z.im);
// 	}
// }

